[package]
name = "autoFav"
version = "0.1.0"
authors = ["NaokiSatou <yomicerisier@gmail.com>"]

[dependencies]
egg-mode = "0.12.0"
dotenv = "0.10.1"
futures = "0.1.14"
tokio-core = "0.1"
chrono = "0.4"
twitter-stream = "0.5"